### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pioryd** [Rydwan678/snake#1]
- [x] Bug - move self direction
- [x] Bug - change speed per level
- [x] Game map
  - [x] center 
  - [x] border
- [x] Scale canvas to screen
  - [x] google...
  - [x] test on big and small screen
- [x] Levels
  - [x] After each level Popup -> "Go to next level"
- [x] Start screen
  - [x] Start Game
- [x] Lose screen
  - [x] Play again
